NAME	= abyss_$(ROLLMPI)_$(ROLLNETWORK)
RELEASE	= 0
RPM.EXTRAS         = AutoReq:No

SRC_SUBDIR	= abyss

ABYSS_NAME	= abyss
ABYSS_VERSION	= 1.3.7
ABYSS_SOURCE	= $(ABYSS_NAME)-$(ABYSS_VERSION).tar.gz

TAR_GZ_PKGS	= $(ABYSS_SOURCE)
